In [2]:
import numpy as np

In [5]:
#creating 1-D array
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [7]:
# creating 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
d=np.zeros((2,2))
print(d)

[[0. 0.]
 [0. 0.]]


In [10]:
#adding two arrays
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


In [12]:
#multiply two arrays
d=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])
f=d*e
print(f)

[[ 5 12]
 [21 32]]


In [14]:
#matrix multiplication
d=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])
i=np.dot(d,e)
print(i)

[[19 22]
 [43 50]]
